# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xset/val_data_bone.npy
  label_path: ./data/ntu120/xset/val_label.pkl
  debug: False

# model
model: model.Sgcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.four_part.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0]
test_batch_size: 256
weights: ./runs/ntu120/ntu120_cset_sgcn_bone_fourpart-49-224750.pt
# ntu120_cset_sgcn_bone_fourpart-41-188790
# ntu120_cset_sgcn_bone_fourpart-43-197780
# ntu120_cset_sgcn_bone_fourpart-45-206770
# ntu120_cset_sgcn_bone_fourpart-47-215760
# ntu120_cset_sgcn_bone_fourpart-49-224750

work_dir: ./work_dir/ntu120/xset/sgcn_test_bone_49
model_saved_name: ./runs/ntu120/ntu120_cset_sgcn_test_bone_49
save_score: True
