work_dir: ./work_dir/ntu120/xsub/sgcn_bone_fourpart
model_saved_name: ./runs/ntu120/ntu120_csub_sgcn_bone_fourpart
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_bone.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_bone.npy
  label_path: ./data/ntu120/xsub/val_label.pkl

# model
model: model.Sgcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.four_part.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30,40]
warm_up_epoch: 5

# training
device: [0]
batch_size: 18
test_batch_size: 64
num_epoch: 50
nesterov: True

only_train_part: True
only_train_epoch: 5
