# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_bone.npy
  label_path: ./data/ntu/xsub/val_label.pkl
  debug: False

# model
model: model.Sgcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.four_part.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0]
test_batch_size: 64
weights: ./runs/ntu_cs_sgcn_bone_fourpart-41-93408.pt 


work_dir: ./work_dir/ntu/xsub/sgcn_test_bone_fourpart
model_saved_name: ./runs/ntu_cs_sgcn_test_bone_fourpart
save_score: True
