# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  label_path: ./data/kinetics/val_label.pkl
  debug: False

# model
model: model.Sgcn.Model
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kf.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 64
weights: ./runs/ki_sgcn_joint_four-59-450780.pt
#ki_sgcn_joint_four-55-420728 36.21
#ki_sgcn_joint_four-57-435754 36.34
#ki_sgcn_joint_four-59-450780 36.40
#ki_sgcn_joint_four-61-465806 36.01
work_dir: ./work_dir/kinetics/sgcn_joint_test
model_saved_name: ./runs/ki_sgcn_joint_test
save_score: True
