# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kinetics/val_data_bone.npy
  label_path: ./data/kinetics/val_label.pkl
  debug: False

# model
model: model.Sgcn.Model
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kf.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 64
weights: ./runs/ki_sgcn_bone_four-59-450780.pt
#ki_sgcn_bone_four-53-405702 31.48
#ki_sgcn_bone_four-55-420728 34.04
#ki_sgcn_bone_four-57-435754 34.09
#ki_sgcn_bone_four-53-405702 34.28
#ki_sgcn_bone_four-61-465806 33.85

work_dir: ./work_dir/kinetics/sgcn_test_bone
model_saved_name: ./runs/ki_sgcn_test_bone
save_score: True
