# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_star_out.npy
  label_path: ./data/ntu/xview/val_label.pkl
  debug: False

# model
model: model.Sgcn_softmax.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.four_part.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0]
test_batch_size: 128
weights: ./runs/shengaotest/cv/ntu_cv_sgcn_starout_fourpart_softmax-48-102312.pt 


work_dir: ./work_dir/ntu_softmax/xview/sgcn_test_starout_fourpart_softmax_128
model_saved_name: ./runs/shengaotest/cv/ntu_cv_sgcn_test_starout_fourpart_softmax_128
save_score: True
